### PR TITLE
Eval sheet fix

### PR DESCRIPTION
**Pull request by pde-bakk**
Whole new file structure and some minor fixes

### CODE REVIEW

**Comment by SaltyMilk** [comment]
Screen Shot 2021-03-17 at 04 53 16
Screen Shot 2021-03-17 at 04 53 06
500 error when I try to /ban auser in chat without being admin of the chat instead of the rails error in screenshot

**Comment by SaltyMilk** [comment]
Went through everything seems really good congratz guys :) ! Should be ready to merge and push for me, after the little bugfix for chat

**Comment by pde-bakk** [comment]
> Screen Shot 2021-03-17 at 04 53 16
> Screen Shot 2021-03-17 at 04 53 06
> 500 error when I try to /ban auser in chat without being admin of the chat instead of the rails error in screenshot

Nice find, I found the issue although I don't understand it.
I added the keyword return to my get_clearence_level method, because otherwise it pointed to the "Clearance_level::User" as an uninitialized constant, but now Rubymine is telling me the return keyword is redundant even though it did fix it.

**Comment by SaltyMilk** [comment]
Ready to merge and push for me.

**Pull request merged**
