### PR TITLE
Fixed issue with allowing dates in the past when creating a new war

### PR DESCRIPTION
**Pull request by pde-bakk**
Also fixed allowing multiple concurrent wartime games.

One issue we still have left is that during a war when either guild reaches the max amount of unanswered match calls (ignored/declined wartime battle invites) the war should be over. I tried to set the war end time early and call the WarEndJob immediately but it didn't work so Sam I'm gonna need your help on this one please.

### CODE REVIEW

**Comment by pde-bakk** [comment]
Now when guild A has ignored/declined X amount (max_unaccepted_match_calls) of wartime battle invites from guild B, guild B can longer send guild A any more wartime invites. guild B will have to wait for tomorrow for another wartime to start for the counter to reset.

Also fixed being able to send wartime battle invites outside of wartime hours

**Review by skrtks — COMMENTED** [review]
I don't see anything that looks off in the code. I'm on my way home now so I'll run some tests at home and approve if I don't find anything.

**Comment by skrtks** [comment]
I think there might be some comparison confusion in checking the wartime:
Screenshot 2021-03-15 at 21 10 42

**Comment by skrtks** [comment]
Is it still possible to edit the max unanswered invites somewhere?

**Comment by pde-bakk** [comment]
Oh nice find I should change the time to 24hr format to fix that issue.
No, max unanswered match calls can only be set at the start of the war, well I mean you can change it in the rails console

**Comment by skrtks** [comment]
If I send a battle request and that request is declined, I can't send a new battle request. I get the following alert: You cannot have more than 1 ongoing wartime battle at a time! However, the request was declined already. I think that the request I tried to send still counts towards the max because after refreshing the page and trying again, I got the warning that the max number of requests was reached.

**Comment by skrtks** [comment]
> Oh nice find I should change the time to 24hr format to fix that issue.
> No, max unanswered match calls can only be set at the start of the war, well I mean you can change it in the rails console

You can just change the check to this: **"if currenttime > wt_begin && currenttime < wt_end"** 24h shouldn't be a problem is it's in datetime

**Comment by pde-bakk** [comment]
> **wt_end"** 24

Huh, actually I could do that since I already change the date on the wt_begin and wt_end if they don't match the current day

**Comment by skrtks** [comment]
There is also a difference between 'and' and &&:

https://www.compassitesinc.com/difference-between-and-and-and-and-or-in-ruby/

**Comment by skrtks** [comment]
I'll check it again tomorrow when a new wt starts ;)

**Comment by pde-bakk** [comment]
Yeah but in this case &&/and doesnt make a difference, also Im fixing it now and I overcomplicated things too much with comparing times. strftime with a 24hr format is actually the easiest so I can just compleletly omit the date and just compare the time element of Time.now and war.wt_begin and war.wt_end.

And Im testing with sending a war invite, declining it and immediately sending another one and it works fine, maybe tomorrow you can show me what went wrong
Im gonna loo

**Comment by pde-bakk** [comment]
Actually I discovered an issue where if you decline invites rapidly you could exceed the limit of unanswered battle invites (because I only increment the counter in the CheckNotificationTimeoutJob), so I decided that even if all users from guild B decline/ignore the battle invite from guild A, it will have to expire before another one can be sent!
Is that okay?

**Comment by skrtks** [comment]
Yes that sounds good!

**Pull request merged**
